export const products = [
  // -------------------- LAPTOPS --------------------
  {
    id: 1,
    name: "MacBook Air M4 Black",
    brand: "Apple",
    price: 119900,
    discountPrice: 109900,
    image: "https://m.media-amazon.com/images/I/71CjP9jmqZL._SL1500_.jpg",
    category: "Laptop",
    rating: 4.8,
    stock: 12,
    color: "Black",
    featured: true,
    description: "Lightweight laptop with M4 chip and long battery life."
  },
  {
    id: 2,
    name: "MacBook Air M4 Gold",
    brand: "Apple",
    price: 119900,
    discountPrice: 111900,
    image: "https://m.media-amazon.com/images/I/71XIkqkx+KL._SL1500_.jpg",
    category: "Laptop",
    rating: 4.9,
    stock: 8,
    color: "Gold",
    featured: false,
    description: "Premium ultra-thin laptop with retina display."
  },
  {
    id: 3,
    name: "Dell XPS 15 OLED",
    brand: "Dell",
    price: 175000,
    discountPrice: 165000,
    image: "https://m.media-amazon.com/images/I/41WrQCyqw1L._SY300_SX300_QL70_FMwebp_.jpg",
    category: "Laptop",
    rating: 4.7,
    stock: 5,
    color: "Silver",
    featured: true,
    description: "High-performance laptop with 4K OLED display."
  },
  {
    id: 4,
    name: "HP Spectre x360",
    brand: "HP",
    price: 145000,
    discountPrice: 139000,
    image: "https://m.media-amazon.com/images/I/41sNgNeF5dL._SY300_SX300_QL70_FMwebp_.jpg",
    category: "Laptop",
    rating: 4.6,
    stock: 14,
    color: "Dark Blue",
    featured: false,
    description: "Premium 2-in-1 convertible laptop with touchscreen."
  },
  {
    id: 5,
    name: "Lenovo ThinkPad X1 Carbon",
    brand: "Lenovo",
    price: 168000,
    discountPrice: 154000,
    image: "https://m.media-amazon.com/images/I/41-oqOMBUDL._SY300_SX300_QL70_FMwebp_.jpg",
    category: "Laptop",
    rating: 4.9,
    stock: 10,
    color: "Black",
    featured: true,
    description: "Business-class durable laptop."
  },

  // -------------------- PHONES --------------------
  {
    id: 6,
    name: "iPhone 15 Pro Max",
    brand: "Apple",
    price: 158000,
    discountPrice: 149999,
    image: "https://m.media-amazon.com/images/I/71657TiFeHL._SL1500_.jpg",
    category: "Phone",
    rating: 4.9,
    stock: 20,
    color: "Natural Titanium",
    featured: true,
    description: "Flagship phone with A17 chip and titanium body."
  },
  {
    id: 7,
    name: "Samsung Galaxy S24 Ultra",
    brand: "Samsung",
    price: 142000,
    discountPrice: 136000,
    image: "https://m.media-amazon.com/images/I/418mFfRZu-L._SY300_SX300_QL70_FMwebp_.jpg",
    category: "Phone",
    rating: 4.8,
    stock: 15,
    color: "Gray",
    featured: false,
    description: "200MP camera and Snapdragon 8 Gen 3."
  },
  {
    id: 8,
    name: "Google Pixel 9 Pro",
    brand: "Google",
    price: 98000,
    discountPrice: 95000,
    image: "https://m.media-amazon.com/images/I/410a3ScPotL._SY300_SX300_QL70_FMwebp_.jpg",
    category: "Phone",
    rating: 4.7,
    stock: 18,
    color: "White",
    featured: true,
    description: "Best AI camera smartphone."
  },
  {
    id: 9,
    name: "OnePlus 12",
    brand: "OnePlus",
    price: 65000,
    discountPrice: 62999,
    image: "https://m.media-amazon.com/images/I/41pR0qlI0yL._SY300_SX300_QL70_FMwebp_.jpg",
    category: "Phone",
    rating: 4.6,
    stock: 25,
    color: "Green",
    featured: false,
    description: "Fast and smooth flagship-level smartphone."
  },
  {
    id: 10,
    name: "Xiaomi 14 Pro +",
    brand: "Xiaomi",
    price: 56000,
    discountPrice: 52999,
    image: "https://m.media-amazon.com/images/I/71532VSTXdL._SX679_.jpg",
    category: "Phone",
    rating: 4.4,
    stock: 30,
    color: "Black",
    featured: false,
    description: "Leica camera flagship phone."
  },

  // -------------------- TABLETS --------------------
  {
    id: 11,
    name: "iPad Pro 11 (12.9 Inch)",
    brand: "Apple",
    price: 129900,
    discountPrice: 125900,
    image: "https://m.media-amazon.com/images/I/31eNrZVuICL._SY300_SX300_QL70_FMwebp_.jpg",
    category: "Tablet",
    rating: 4.9,
    stock: 10,
    color: "Space Black",
    featured: true,
    description: "Most powerful iPad ever with M4 chip."
  },
  {
    id: 12,
    name: "Samsung Galaxy Tab S9 FE+",
    brand: "Samsung",
    price: 110000,
    discountPrice: 105000,
    image: "https://m.media-amazon.com/images/I/61OjlkoljyL._SX450_.jpg",
    category: "Tablet",
    rating: 4.8,
    stock: 12,
    color: "Silver",
    featured: false,
    description: "Large AMOLED tablet with S-Pen."
  },
  {
    id: 13,
    name: "Xiaomi Pad 7 ",
    brand: "Xiaomi",
    price: 28999,
    discountPrice: 25999,
    image: "https://m.media-amazon.com/images/I/41jnbl0tCmL._SY300_SX300_QL70_FMwebp_.jpg",
    category: "Tablet",
    rating: 3.5,
    stock: 22,
    color: "Graphite Grey",
    featured: false,
    description: "Affordable and fast tablet."
  },
  {
    id: 14,
    name: "Lenovo Tab P12 Pro",
    brand: "Lenovo",
    price: 62000,
    discountPrice: 59999,
    image: "https://m.media-amazon.com/images/I/51lQoWrcdQL._SY300_SX300_QL70_FMwebp_.jpg",
    category: "Tablet",
    rating: 4.6,
    stock: 16,
    color: "Black",
    featured: false,
    description: "AMOLED tablet with premium build."
  },
  {
    id: 15,
    name: "iPad 10th Gen",
    brand: "Apple",
    price: 32999,
    discountPrice: 30999,
    image: "https://m.media-amazon.com/images/I/31Wj0j4RXhL._SY300_SX300_QL70_FMwebp_.jpg",
    category: "Tablet",
    rating: 4.4,
    stock: 25,
    color: "Silver",
    featured: false,
    description: "Best budget iPad for students."
  },

  // -------------------- EARBUDS --------------------
  {
    id: 16,
    name: "AirPods Pro 2",
    brand: "Apple",
    price: 24999,
    discountPrice: 22999,
    image: "https://m.media-amazon.com/images/I/61SUj2aKoEL.SL1500.jpg",
    category: "Earbuds",
    rating: 4.9,
    stock: 40,
    color: "White",
    featured: true,
    description: "Top-tier ANC earbuds."
  },
  {
    id: 17,
    name: "Samsung Galaxy Buds 2 Pro",
    brand: "Samsung",
    price: 18999,
    discountPrice: 16999,
    image: "https://m.media-amazon.com/images/I/21Y3xVnL0BL._SX300_SY300_QL70_FMwebp_.jpg",
    category: "Earbuds",
    rating: 4.8,
    stock: 35,
    color: "Black",
    featured: false,
    description: "24-bit HiFi audio earbuds."
  },
  {
    id: 18,
    name: "Sony WF-1000XM5",
    brand: "Sony",
    price: 23999,
    discountPrice: 21999,
    image: "https://m.media-amazon.com/images/I/61GJAFdM9pL._SX450_.jpg",
    category: "Earbuds",
    rating: 4.8,
    stock: 12,
    color: "Black",
    featured: true,
    description: "Industry-leading noise cancellation."
  },
  {
    id: 19,
    name: "OnePlus Buds Pro 2",
    brand: "OnePlus",
    price: 11999,
    discountPrice: 10999,
    image: "https://m.media-amazon.com/images/I/512ch1TdARL._SX569_.jpg",
    category: "Earbuds",
    rating: 4.5,
    stock: 16,
    color: "Green",
    featured: false,
    description: "Spatial audio earbuds."
  },
  {
    id: 20,
    name: "boAt Airdopes Prime 701 ANC",
    brand: "boAt",
    price: 7990,
    discountPrice: 1899,
    image: "https://m.media-amazon.com/images/I/31uM+yTKaZL._SY300_SX300_QL70_FMwebp_.jpg",
    category: "Earbuds",
    rating: 4.2,
    stock: 50,
    color: "Red",
    featured: false,
    description: "Affordable bass-heavy earbuds."
  },

  // -------------------- SMARTWATCHES --------------------
  {
    id: 21,
    name: "Apple Watch Series 10",
    brand: "Apple",
    price: 45999,
    discountPrice: 43999,
    image: "https://m.media-amazon.com/images/I/41-FVCT1tXL._SX342_SY445_QL70_FMwebp_.jpg",
    category: "Smartwatch",
    rating: 4.9,
    stock: 15,
    color: "Black",
    featured: true,
    description: "Advanced fitness and health watch."
  },
  {
    id: 22,
    name: "Samsung Galaxy Watch 7",
    brand: "Samsung",
    price: 32999,
    discountPrice: 30999,
    image: "https://m.media-amazon.com/images/I/71d7quY-KxL._SX679_.jpg",
    category: "Smartwatch",
    rating: 4.7,
    stock: 18,
    color: "Silver",
    featured: false,
    description: "AMOLED display premium smartwatch."
  },
  {
    id: 23,
    name: "Amazfit GTR 4",
    brand: "Amazfit",
    price: 16999,
    discountPrice: 14999,
    image: "https://m.media-amazon.com/images/I/41uaXPCW73L._SY300_SX300_QL70_FMwebp_.jpg",
    category: "Smartwatch",
    rating: 4.5,
    stock: 30,
    color: "Black",
    featured: false,
    description: "Long battery life with accurate GPS."
  },
  {
    id: 24,
    name: "Noise ColorFit Ultra 3",
    brand: "Noise",
    price: 3499,
    discountPrice: 2999,
    image: "https://m.media-amazon.com/images/I/41APgGFuriL._SY300_SX300_QL70_FMwebp_.jpg",
    category: "Smartwatch",
    rating: 4.3,
    stock: 45,
    color: "Black",
    featured: false,
    description: "Budget smartwatch with large display."
  },
  {
    id: 25,
    name: "Fire-Boltt Phoenix Pro",
    brand: "Fire-Boltt",
    price: 2899,
    discountPrice: 2499,
    image: "https://m.media-amazon.com/images/I/819DWQLgjKL._SY450_.jpg",
    category: "Smartwatch",
    rating: 4.2,
    stock: 48,
    color: "Rose Gold",
    featured: false,
    description: "Feature-rich budget smartwatch."
  },

  // -------------------- ACCESSORIES --------------------
  {
    id: 26,
    name: "Apple 20W USB-C Adapter",
    brand: "Apple",
    price: 1599,
    discountPrice: 1499,
    image: "https://m.media-amazon.com/images/I/61vtLhO6fDL.SL1500.jpg",
    category: "Accessories",
    rating: 4.7,
    stock: 100,
    color: "White",
    featured: false,
    description: "Fast charger for iPhones."
  },
  {
    id: 27,
    name: "Samsung 45W Super Fast Charger",
    brand: "Samsung",
    price: 2999,
    discountPrice: 2699,
    image: "https://m.media-amazon.com/images/I/317U9ilDc4L._SY300_SX300_QL70_FMwebp_.jpg",
    category: "Accessories",
    rating: 4.6,
    stock: 80,
    color: "Black",
    featured: false,
    description: "High-speed charging adapter."
  },
  {
    id: 28,
    name: "Anker 20,000mAh Powerbank",
    brand: "Anker",
    price: 3499,
    discountPrice: 3199,
    image: "https://m.media-amazon.com/images/I/31qkEjeWyxL._SY300_SX300_QL70_FMwebp_.jpg",
    category: "Accessories",
    rating: 4.8,
    stock: 60,
    color: "Black",
    featured: false,
    description: "Long-lasting high-capacity powerbank."
  },
  {
    id: 29,
    name: "Logitech MX Master 3S Mouse",
    brand: "Logitech",
    price: 10999,
    discountPrice: 10499,
    image: "https://m.media-amazon.com/images/I/61xKiCADfpL._SX679_.jpg",
    category: "Accessories",
    rating: 4.8,
    stock: 22,
    color: "Gray",
    featured: true,
    description: "Best wireless productivity mouse."
  },
  {
    id: 30,
    name: "AKG Type-C Earphones",
    brand: "AKG",
    price: 1499,
    discountPrice: 1199,
    image: "https://m.media-amazon.com/images/I/712lQt2exJL._SX450_.jpg",
    category: "Accessories",
    rating: 4.5,
    stock: 90,
    color: "Black",
    featured: false,
    description: "High-quality wired Type-C earphones."
  },

  // ----------- EXTRA PRODUCTS (31–35) ----------
  {
    id: 31,
    name: "Oppo Reno 12 Pro",
    brand: "Oppo",
    price: 49999,
    discountPrice: 46999,
    image: "https://m.media-amazon.com/images/I/51AVBqkFR6L._SY606_.jpg",
    category: "Phone",
    rating: 4.4,
    stock: 26,
    color: "Space Brown",
    featured: false,
    description: "Stylish premium camera phone."
  },
  {
    id: 32,
    name: "Vivo X300 Pro",
    brand: "Vivo",
    price: 119999,
    discountPrice: 109999,
    image: "https://m.media-amazon.com/images/I/419CYQ4W6EL._SY300_SX300_QL70_FMwebp_.jpg",
    category: "Phone",
    rating: 4.6,
    stock: 14,
    color: "Dune Gold",
    featured: true,
    description: "Flagship camera with ZEISS optics."
  },
  {
    id: 33,
    name: "Redmi Pad SE",
    brand: "Realme",
    price: 17999,
    discountPrice: 15999,
    image: "https://m.media-amazon.com/images/I/71gRAJn8qiL._SX450_.jpghttps://m.media-amazon.com/images/I/41YN6hEgBTL._SY300_SX300_QL70_FMwebp_.jpg",
    category: "Tablet",
    rating: 4.3,
    stock: 33,
    color: "Gray",
    featured: false,
    description: "Sleek and affordable tablet."
  },
  {
    id: 34,
    name: "Asus ROG Strix G16",
    brand: "Asus",
    price: 155000,
    discountPrice: 145000,
    image: "https://m.media-amazon.com/images/I/41R+riD5i9L._SY300_SX300_QL70_FMwebp_.jpg",
    category: "Laptop",
    rating: 4.7,
    stock: 9,
    color: "Eclipse Gray",
    featured: true,
    description: "Ultimate gaming laptop with RTX 4080."
  },
  {
    id: 35,
    name: "Boat Wave Sigma Smartwatch",
    brand: "boAt",
    price: 2499,
    discountPrice: 2199,
    image: "https://m.media-amazon.com/images/I/71JaNi+RfrL._AC_CR0%2C0%2C0%2C0_SX480_SY360_.jpg",
    category: "Smartwatch",
    rating: 4.1,
    stock: 70,
    color: "Black",
    featured: false,
    description: "Budget Bluetooth-calling smartwatch."
  }
];

